import os
import sys

env=DefaultEnvironment().Clone()
LIB_DIR=os.environ['LIB_DIR'];

env['CPPPATH'] = env['CPPPATH'] + [
  os.path.join('../../', '3rd/ffmpeg/FFmpeg')
]

env.Library(os.path.join(LIB_DIR, 'media_player'), Glob('*.c'))
